title: ARACROQ
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  1-legumes:
    title: "Légumes, fruits, plants"
    output: true
  2-viandes:
    title: "Viandes"
    output: true
  3-fromages:
    title: "Fromages, yaourts"
    output: true
  4-bieres:
    title: "Bières"
    output: true
  5-miels:
    title: "Miel & dérivés"
    output: true
  6-pains:
    title: "Pains"
    output: true  
  7-tisanes:
    title: "Tisanes, petites fleurs, confitures, baumes"
    output: true
  8-oeufs:
    title: "Œufs"
    output: true
  9-autres:
    title: "Autres transformations"
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
