title: ARACROQ
description: >
  Le site Aracroq propose un annuaire des producteurs locaux et des initiatives artisanales en vallée de l'Arac,
  avec un focus particulier sur les circuits courts. Il vise à mettre en valeur le savoir-faire des personnes artisanes, 
  agricultrices, et productrices de cette vallée, en facilitant l'accès à des produits locaux de qualité.
  Aracroq offre une plateforme pour découvrir les richesses du territoire, soutenir les économies locales, 
  et promouvoir des modes de consommation responsables. Que vous soyez un habitant ou un visiteur, 
  le site vous invite à explorer la diversité des offres et à participer à la vie économique et culturelle de la vallée de l'Arac.
baseline: Les acteurs et actrices du circuit-court de la vallée de l'Arac
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  1-legumes:
    title: "Légumes, fruits, plants"
    output: true
  2-viandes:
    title: "Viandes"
    output: true
  3-fromages:
    title: "Fromages, yaourts"
    output: true
  4-bieres:
    title: "Bières"
    output: true
  5-miels:
    title: "Miel & dérivés"
    output: true
  6-pains:
    title: "Pains"
    output: true  
  7-tisanes:
    title: "Tisanes, petites fleurs, confitures, baumes"
    output: true
  8-oeufs:
    title: "Œufs"
    output: true
  9-autres:
    title: "Autres transformations"
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
