title: ARACROQ
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  legumes:
    output: true
  viandes:
    output: true
  fromages:
    output: true
  bieres:
    output: true
  pains:
    output: true  
  tisanes:
    output: true
  oeufs:
    output: true
  autres:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
